module.exports = {
  "Jamie": [
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada", // Thanksgiving
    "Waterloo, Canada",
    "Hamilton, Canada", // ACM Regionals
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2010 (1B) - Velocity
    "Waterloo, Canada",
    // March -> August 2010 (TWG)
    "Toronto, Canada",
    // September -> December 2010 (2A) - Glenelm
    "Waterloo, Canada",
    "London, Canada", // Yuxuan's 19th
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Niagara Falls, Canada", // 2 yr anniv
    "Waterloo, Canada",
    "Ottawa, Canada",
    // January -> April 2011 (Kontagent)
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    // May -> August 2011 (2B) - Glenelm
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    // September -> December 2011 (Facebook)
    "Ottawa, Canada",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2012 (3A) - Velocity
    "Toronto, Canada",
    "Waterloo, Canada",
    "Montreal, Canada", // CUSEC
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // May -> August 2013 (Khan Academy, Remote from Toronto)
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Mountain View, California", // Visit KA
    "Toronto, Canada",
    "Waterloo, Canada", // Badminton Tournament
    "Toronto, Canada",
    "Montreal, Canada", // Cruise cancelled
    "Toronto, Canada",
    "New York, New York", // Trip with SE friends
    "Toronto, Canada",
    // September -> December 2012 (3B) - 350 Lester
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada",
    "Montreal, Canada",
    // January -> April 2013 (Square)
    "Ottawa, Canada",
    "San Francisco, California",
    "Los Angeles, California",
    "San Francisco, California",
    "Tahoe, California",
    "San Francisco, California",
    "Mountain View, California",
    "San Francisco, California",
    "Tahoe, California",
    "San Francisco, California",
    "Yosemite National Park, California",
    "San Francisco, California",
    "Waikiki, Hawaii",
    "San Francisco, California",
    // May -> August 2013 (4A) - 350 Lester
    "Ottawa, Canada",
    "Waterloo, Canada",
    "Niagara Falls, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // TODO(jlfwong): Camping?

    // September -> December 2013 (Eurotrip)
    "Ottawa, Canada",
    "Toronto, Canada",
    "Rome, Italy",
    "Florence, Italy",
    "La Spezia, Italy",
    "Venice, Italy",
    "Copenhagen, Denmark",
    "Amsterdam, Holland",
    "London, England",
    "Lyon, France",
    "Paris, France",
    "Toulouse, France",
    "Barcelona, Spain",
    "Granada, Spain",
    "Madrid, Spain",
    "Dublin, Ireland",
    "Edinburgh, Scotland",
    "London, England",
    "Oslo, Norway",
    "Brussels, Belgium",
    "Berlin, Germany",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "San Jose, California",
    "San Francisco, California",
    "San Jose, California",
    "San Francisco, California",
    "Ottawa, Canada",
    "Kauai, Hawaii",
    "Ottawa, Canada"
  ],
  // TODO(jlfwong): Make sure this is right, I think the copy paste may have
  // fucked up...
  "Becky": [
    "Ottawa, Ontario, Canada",
    "Hibaldstow, North Lincolnshire, England",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Windermere, British",
    "Columbia, Canada",
    "Ottawa, Ontario, Canada",
    "New York City, USA",
    "Ottawa, Ontario, Canada",
    "Hibaldstow, North Lincolnshire, England",
    "Ottawa, Ontario, Canada",
    "Oshawa, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Oshawa, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Westmeath, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Kingston, Ontario, Canada",
    "Bradford, West Yorkshire, England",
    // "Ilfracombe, North Devon Coast, England",
    "Chepstow, England",
    "Hibaldstow, North Lincolnshire, England",
    "Manchester, England",
    "Ottawa, Ontario, Canada",
    "Kingston, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Mt. Tremblant, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Murphy’s Point, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Hibaldstow, North Lincolnshire, England",
    "Westmeath, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // "Samuel de Champlain Provincial Park, Ontario, Canada",
    // "Pancake Bay, Sault Ste Marie, Ontario, Canada",
    "Kakabeka Falls, Ontario, Canada",
    "Rushing River, Kenora, Ontario",
    "Crooked Lake, Saskatchewan, Canada",
    "Calgary, Alberta, Canada",
    "Paris, France",
    "Ottawa, Ontario, Canada",
    "Mt. Tremblant, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Kingston, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Burlington, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Kingston, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Lake Windermere, British",
    "Columbia, Canada",
    "Waterton, Alberta, Canada",
    "Missoula, Montana, USA",
    "West Yellowstone, Montana, USA",
    "Greybull, Wyoming, USA",
    "Rapid City, South Dakota, USA",
    "Sioux Falls, South Dakota, USA",
    "Cloquet, Minnesota, USA",
    "Newberry, Michigan, USA",
    "Massey, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Riviere du Loup, Quebec, Canada",
    "Truro, Nova Scotia, Canada",
    "Port aux Basques, Newfoundland, Canada",
    "Clarenville, Newfoundland, Canada",
    "St. John’s, Newfoundland, Canada",
    // "Terra Nova, National Park, Newfoundland, Canada",
    "Sydney, Nova Scotia, Canada",
    "Trenton, Nova Scotia, Canada",
    "Panmure Island, Prince Edward Island, Canada",
    "Charlottetown, Prince Edward Island, Canada",
    "Penobsquis, New Brunswick, Canada",
    "Skowhegan, Maine, USA",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Farrelton, Quebec, Canada",
    "Montreal, Quebec, Canada",
    "Farrelton, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Huntsville, Ontario, Canada",
    "Reading, Pennsylvania, USA",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Huntsville, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Huntsville, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Milan, Italy",
    "Venice, Italy",
    "Florence, Italy",
    "Assisi, Italy",
    "Sorrento, Italy",
    "Rome, Italy",
    "Ottawa, Ontario, Canada",
    "Huntsville, Ontario, Canada",
    // "Kipawa Valley River, Ontario, Canada",
    "Huntsville, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // "Silver Sands, Jamaica",
    "Ottawa, Ontario, Canada",
    "Hueco Tanks, Texas, USA",
    "Ottawa, Ontario, Canada",
    "Hong Kong",
    "Melbourne, Victoria, Australia",
    "Canberra, New South Wales, Australia",
    "Surfers Paradise, Gold Coast, Queensland, Australia",
    "Sydney, New South Wales, Australia",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada ",
    "Calgary, Alberta, Canada",
    "Bishop, California, USA",
    "Calgary, Alberta, Canada",
    "Edmonton, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Penticton, British",
    "Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Canmore, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Quepos, Costa Rica",
    "Edmonton, Alberta, Canada",
    "McBride, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Canmore, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "San Jose, Costa Rica",
    "Santa Teresa, Costa Rica",
    "San Jose, Costa Rica",
    "Calgary, Alberta, Canada",
    "Canmore, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Alicante, Spain",
    "Valencia, Spain",
    "Oropesa del Mar, Spain",
    "Barcelona, Spain",
    // "Pleta de Baqueira, Baqueira-Beret, Vaqueira, Spain",
    "Zarautz, Spain",
    "San Sebastian, Spain",
    "Barcelona, Spain",
    "Edenthorpe, England",
    "Paris, France",
    "Interlaken, Switzerland",
    "Grindelwald, Switzerland",
    "Interlaken, Switzerland",
    "Grindelwald, Switzerland",
    "Calgary, Alberta, Canada",
    "Varadero, Cuba",
    "Ottawa, Ontario, Canada",
    "Crested Butte, Colorado, USA",
    "Denver, Colorado, USA",
    "Interlaken, Switzerland",
    "Ottawa, Ontario, Canada",
    "London, Ontario, Canada",
    "Crested Butte, Colorado, USA",
    "Breckenridge, Colorado, USA",
    "Crested Butte, Colorado, USA",
    "Ottawa, Ontario, Canada",
    "Beach, Kauai, Hawaii, USA",
    "Crested Butte, Colorado",
    "Santa Teresa, Costa Rica",
    "San Jose, Costa Rica",
    "Crested Butte, Colorado, USA",
    "Malibu, California, USA",
    "Grand Canyon National Park, USA",
    "Moab, Utah, USA",
    "Saint Paul, Minneapolis, Minnesota, USA",
    "Crested Butte, Colorado, USA",
    "Calgary, Alberta, Canada",
    "Crested Butte, Colorado, USA",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Saint Paul, Minneapolis, Minnesota, USA",
    "Calgary, Alberta, Canada",
    "Houston, Texas, USA",
    "Santa Teresa, Costa Rica",
    "Houston, Texas, USA",
    "Calgary, Alberta, Canada",
    "Fernie, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Napanee, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Toronto, Ontario, Canada",
    "Addis Ababa, Ethiopia",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Sina, Ethiopia",
    "Debre Birhan, Ethiopia",
    "Ankober, Ethiopia",
    "Debre Sina, Ethiopia",
    "Addis Ababa, Ethiopia",
    "Nazret, Ethiopia",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Victoria, British Columbia, Canada",
    // "Pacific Rim National Park, Vancouver Island, British Columbia, Canada",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    "Golden, British Columbia, Canada",
    "Winnipeg, Manitoba, Canada",
    "Montreal, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Auckland, New Zealand",
    "Kaitaia, New Zealand",
    "Ahipara, New Zealand",
    "Auckland, New Zealand",
    "Whitianga, New Zealand",
    "Tauranga, New Zealand",
    "Rotorua, New Zealand",
    "Taupo, New Zealand",
    "Palmerston North, New Zealand",
    "Wellington, New Zealand",
    "Picton, New Zealand",
    "Greymouth, New Zealand",
    // "Franz Joseph, New Zealand",
    "Wanaka, New Zealand",
    "Queenstown, New Zealand",
    "Invercargill, New Zealand",
    "Dunedin, New Zealand",
    "Oamaru, New Zealand",
    "Christchurch, New Zealand",
    "Nelson, New Zealand",
    "Motueka, New Zealand",
    "Abel Tasman National Park, New Zealand",
    "Winnipeg, Manitoba, Canada",
    "Nelson, New Zealand",
    "Wellington, New Zealand",
    "Palmerston North, New Zealand",
    // "Tongariro National Park, New Zealand",
    "Hamilton, New Zealand",
    "Auckland, New Zealand",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Penticton, British Columbia, Canada",
    "Vancouver, British Columbia, Canada",
    "Winnipeg, Manitoba, Canada",
    "Churchill, Manitoba, Canada",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Clear Lake, Manitoba, Canada",
    "Winnipeg, Manitoba, Canada",
    "Rosthern, Saskatchewan, Canada",
    // "Wabasca, Slave Lake, Alberta, Canada",
    // "Old Man River, Coleman, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Slave Lake, Alberta, Canada",
    "Vancouver, British Columbia, Canada",
    "Kamloops, British Columbia, Canada",
    "East Barriere Lake, British Columbia, Canada",
    "Kamloops, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Regina, Saskatchewan, Canada",
    "Winnipeg, Manitoba, Canada",
    "Mazatlan, Mexico",
    "Sayulita, Mexico",
    "Guadalajara, Mexico",
    "Mexico City, Mexico",
    "Tequila, Mexico",
    "Sayulita, Mexico",
    "Mazatlan, Mexico",
    "Winnipeg, Manitoba, Canada",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Vanscoy, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Edmonton, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Vanscoy, Saskatchewan, Canada",
    // "Ness Creek, Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Regina, Saskatchewan, Canada",
    "Winnipeg, Manitoba, Canada",
    "Thunder Bay, Ontario, Canada",
    "Sault Ste Marie, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // "St. Agathe des Monts, Quebec, Canada",
    "Toronto, Ontario, Canada",
    "Sault Ste Marie, Ontario, Canada",
    "Thunder Bay, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Regina, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Moose Jaw, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    // "Ness Creek, Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Cardross, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Birch Lake, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Birch Lake, Saskatchewan, Canada",
    // "Old Man River, Coleman, Alberta, Canada",
    "Blairmore, Alberta, Canada",
    "Ymir, British Columbia, Canada",
    // "Kaslow, British Columbia, Canada",
    "Kamloops, British Columbia, Canada",
    "Vancouver, British Columbia, Canada",
    "Sechelt, British Columbia, Canada",
    "Ottawa, Ontario, Canada",
    "Britannia Beach, Squamish, British Columbia, Canada",
    "Cache Creek, British Columbia, Canada",
    "Jasper, Alberta, Canada",
    "Edmonton, Alberta, Canada",
    "Saskatoon, Saskatchewan, Canada",
    // "Ness Creek, Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Turtle Lake, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Lethbridge, Alberta, Canada",
    "Saskatoon, Saskatchewan, Canada",
    // "Ness Creek, Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Ottawa, Ontario, Canada",
    "Saskatoon, Saskatchewan, Canada",
    // "Clearwater, Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    // "Clearwater, Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada"
  ]
};
